services:
  haproxy:
    image: haproxytech/haproxy-debian:s6-latest
    ports:
      - "5555:5555"
      - "18081:18081"
      - "18082:18082"
    volumes:
      - ${HAPROXY_CONFIG_DIR:-./dev/haproxy}:/usr/local/etc/haproxy
    depends_on:
      - consul
      - echo

  consul:
    image: hashicorp/consul:1.17
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -bind=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"

  echo:
    image: hashicorp/http-echo:1.0
    command: ["-text=hello-from-consul", "-listen=:5678"]
